---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceResolver
metadata:
  name: api
spec:
  subsets:
    api-primary:
      filter: "Service.ID contains \"api-deployment-primary\""
      onlyPassing: false
    api-canary:
      filter: "Service.ID not contains \"api-deployment-primary\""
      onlyPassing: false


---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceRouter
metadata:
  name: api
spec:
  routes:
  - destination:
      service: "api"
      numRetries: 3
      retryOnStatusCodes: [503]

---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceSplitter
metadata:
  name: api
spec:
  splits:
    - weight: 0
      serviceSubset: api-primary
    - weight: 100
      serviceSubset: api-canary