
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceSplitter
metadata:
  name: api
spec:
  splits:
    - weight: 0
      serviceSubset: api-primary
    - weight: 100
      serviceSubset: api-canary