---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: default
  labels:
    app: metrics
spec:
  selector:
    app: api
  ports:
    - name: http
      protocol: TCP
      port: 9090
      targetPort: 9090
    - name: metrics # prom scraping port
      protocol: TCP
      port: 20200
      targetPort: 20200

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
  namespace: default
automountServiceAccountToken: false