name: Release Workflow

on: 
  pull_request:
    types: [closed]

jobs:

  release:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
    - id: bump
      uses: zwaldowski/match-label-action@v1
      with:
        allowed: patch
      
    - name: Echo
      run: echo "${{ steps.bump.outputs.match }}"